### ISSUE TITLE
Show an error message right after quitting the program.

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#54] opened 2017-11-09 17:51 UTC
Show an error message right after quitting the program. (not minimizing)
platform: windows-10-32bit

![capture](https://user-images.githubusercontent.com/8821870/32620592-28bc0558-c5b9-11e7-92c9-458ced62f3be.PNG)

**Comment by tamlok** [comment] 2017-11-10 11:30
Hi, thanks for using VNote and reporting issues.

1. Do you enable the "minimize to system tray after closing"? If enabled, please try to disable it and test again;
2. For now I do not have win10-32bit in hand. I will try to reproduce it in VM later. It used to work fine in win7-32bit.

Thanks!

**Comment by seaspeak** [comment] 2017-11-10 15:02
'minimize to system tray after closing' is disabled. If it is enabled, the program can quit by right-click on the system tray icon without problem.

My system Microsoft Windows [Version 10.0.14393] 32-bit

**Comment by tamlok** [comment] 2017-11-10 15:14
Will `Ctrl+Q` quitting VNote trigger this issue?

**Comment by seaspeak** [comment] 2017-11-10 15:17
No.

**Comment by tamlok** [comment] 2017-11-12 10:17
Hi, I ran VNote in Win 10 32-bit VM but could not reproduce the crash. I suggest that you could try the latest build [here](https://bintray.com/tamlok/vnote/vnote/1.9) to see if that crash still exists.

Thanks!

**Comment by seaspeak** [comment] 2017-11-12 13:49
'new' 1.9? the symptom is gone, anyway. Thanks.

**Comment by tamlok** [comment] 2017-11-12 14:12
Coll! VNote has a continuous build which cpntains the latest changes.

**Closed by tamlok** 2017-11-12 14:12 UTC
