### ISSUE TITLE
Rendering of # *italic*

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#104] opened 2018-01-16 11:16 UTC
Rendering of `# *italic*` is inconsistent under edit mode and read mode.

**Comment by tamlok** [comment] 2018-01-17 12:18
Hi, this is caused by the same bug in #105 . It has been fixed in (217eafd91bdf8e256c6b8905edb68070dc475e1f).

![image](https://user-images.githubusercontent.com/5763157/35042417-86ec4206-fbc3-11e7-8d53-1683dbbb1f1d.png)

Thanks!

**Closed** 2018-01-18 00:40 UTC
